services:
  bloogla:
    build: .
    container_name: bloogla_cms
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./bloogla.json:/app/bloogla.json
    environment:
      - DATABASE_URL=sqlite:///app/data/bloogla.db
      - RUST_LOG=info
